### ISSUE TITLE
When serializing, convert to camel case

### ISSUE THREAD

**Issue by RangerMauve** [cosmosio/get-dataset#1]
According to the [spec](https://html.spec.whatwg.org/multipage/dom.html#dom-dataset), attributes with multiple words should be converted to camel case.

So with this example:

``` html
<div data-cats="meow" data-are-great="true"></div>
```

With your serialization it will be converted to:

``` json
{
  "cats": "meow",
  "are-great": "true"
}
```

Where as the native dataset would look like

``` json
{
  "cats": "meow",
  "areGreat": "true"
}
```

**Comment by podefr** [comment]
Awesome, thanks for pointing out! I'll publish as soon as I can

**Comment by RangerMauve** [comment]
Fastest way might be with [this module](https://www.npmjs.com/package/to-camel-case)

**Comment by podefr** [comment]
Just pushed 0.0.2 with the fix, thanks a lot for the bug report! Let me know if anything else comes up

**Comment by RangerMauve** [comment]
Thanks for the quick fix, too! I'm gonna be using it a bunch very soon, so I'll post if anything else can be improved.

**Comment by podefr** [comment]
awesome!
